version: '3'
services:
  redis-mg:
    image: redis
    expose:
      - 6379

  postgres-mg:
    image: postgres:11.7
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: ${DB_STORAGE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ${DB_STORAGE}:/var/lib/postgresql/data

  php7.4-mg:
    build:
      context: docker/php
      dockerfile: php.docker
    container_name: php7.4-mg
    ports:
      - 9000:9000
    volumes:
      - ${PHP_INI_PATH}:/usr/local/etc/php/php.ini
      - ${APPLICATION_PATH}:/var/www/html
    links:
      - redis-mg

  nginx-mg:
    image: nginx:stable-alpine
    volumes:
      - ${APPLICATION_PATH}:/var/www/html
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    links:
      - php7.4-mg