version: '3'
services:
  redis-mg:
    image: redis
    expose:
      - 6379
    networks:
      - mg-network

#  pgsql-mg:
#    image: postgres:9.6.6-alpine
#    #    restart: unless-stopped
#    ports:
#      - ${DB_PORT}:5432
#    environment:
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_DB: ${DB_DATABASE}
#    networks:
#      - mg-network

  php7.3-mg:
    build:
      context: docker/php
      dockerfile: php.docker
    container_name: php7.3-mg
    ports:
      - "9000:9000"
#    expose:
#      - "9000"
    volumes:
      - ${PHP_INI_PATH}:/usr/local/etc/php/php.ini
      - ${APPLICATION_PATH}:/var/www/html
    links:
#      - pgsql-mg
      - redis-mg
    networks:
      - mg-network

  nginx-up:
    image: nginx:stable-alpine
    volumes:
      - ${APPLICATION_PATH}:/var/www/html:cached
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    links:
      - php7.3-mg
#      - pgsql-mg
    networks:
      - mg-network


networks:
  mg-network:
    driver: bridge